### ISSUE TITLE
After installing and creating a new user, can't log in

### ISSUE THREAD

**Issue by Derkades** [ccarney16/pterodactyl-docker#23]
When I click the log-in button I get redirected back to the login page. `docker logs ptero_panel` only shows nginx access logs. Creating an new user according to the instructions in INSTALL.md went fine without errors. I even got an email. The error.log in the log directory is blank and there is no laravel log file.

During debugging I noticed that some of the files in /var/www/html were owned by root and some by nginx, so I ran `chmod -R nginx:nginx /var/www/html` but that didn't fix the issue.

My docker compose file:
```
  ptero_redis:
    container_name: 'ptero_redis'
    image: redis:alpine
    restart: unless-stopped
  
  ptero_db:
    container_name: 'ptero_db'
    image: 'mariadb:10.2'
    volumes: 
      - '/srv/pterodactyl/db:/var/lib/mysql'
    restart: unless-stopped
    environment:
      - 'MYSQL_ROOT_PASSWORD=pp'
      - 'MYSQL_DATABASE=pp'
      - 'MYSQL_USER=pp'
      - 'MYSQL_PASSWORD=pp'
  
  ptero_panel:
    container_name: 'ptero_panel'
    depends_on: [ptero_redis, ptero_db]
    image: ccarney16/pterodactyl-panel:latest
    restart: unless-stopped
    volumes:
      - '/srv/pterodactyl/panel:/data'
    ports:
      - '127.0.0.1:5003:80'
    environment:
      - 'SSL=false' # SSL is handled by nginx reverse proxy
      - 'DISABLE_WORKERS=false'
      - 'APP_URL=redacted'
      - 'TIMEZONE=Europe/Amsterdam'
      - 'CACHE_DRIVER=redis'
      - 'REDIS_HOST=ptero_redis'
      - 'REDIS_PORT=6379'
      - 'DB_HOST=ptero_db'
      - 'DB_PORT=3306'
      - 'DB_DATABASE=pp'
      - 'DB_USERNAME=pp'
      - 'DB_PASSWORD=pp'
      - 'MAIL_DRIVER=smtp'
      - 'MAIL_HOST=smtp-mail.outlook.com'
      - 'MAIL_PORT=587'
      - 'MAIL_ENCRYPTION=tls'
      - 'MAIL_USERNAME=redacted'
      - 'MAIL_PASSWORD=redacted'
      - 'MAIL_FROM=redacted'
      - 'PTERODACTYL_CLIENT_DATABASES_ALLOW_RANDOM=false'
      - 'RECAPTCHA_ENABLED=false'
```
