### ISSUE TITLE
Got 'Bad Gateway' when putting daemon behind jwilder/nginx-proxy

### ISSUE THREAD

**Issue by Lukaesebrot** [ccarney16/pterodactyl-docker#38]
Hey^^

I am trying to set up Pterodactyl using Docker and managed to start the database and panel. I am using jwilder/nginx-proxy to enable SSL and reverse proxying, my compose file looks like this:
```
version: '3'

services:
  nginx:
    image: nginx
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./data/conf:/etc/nginx/conf.d
      - ./data/vhost:/etc/nginx/vhost.d
      - ./data/html:/usr/share/nginx/html
      - ./data/certs:/etc/nginx/certs
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy=true"

  dockergen:
    image: jwilder/docker-gen
    container_name: nginx-proxy-gen
    restart: always
    depends_on:
      - nginx
    command: -notify-sighup nginx-proxy -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    volumes:
      - ./data/conf:/etc/nginx/conf.d
      - ./data/vhost:/etc/nginx/vhost.d
      - ./data/html:/usr/share/nginx/html
      - ./data/certs:/etc/nginx/certs
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx-proxy-le
    restart: always
    depends_on:
      - nginx
      - dockergen
    environment:
      NGINX_PROXY_CONTAINER: nginx-proxy
      NGINX_DOCKER_GEN_CONTAINER: nginx-proxy-gen
    volumes:
      - ./data/conf:/etc/nginx/conf.d
      - ./data/vhost:/etc/nginx/vhost.d
      - ./data/html:/usr/share/nginx/html
      - ./data/certs:/etc/nginx/certs
      - /var/run/docker.sock:/var/run/docker.sock:ro

networks:
  default:
    external:
      name: nginx-proxy
```

After I started that proxy, I start Pterodactyl using the following compose file:
```
version: '3'

services:
  mysql:
    env_file: .env
    image: mariadb:10.2
    container_name: ptero-db
    restart: always
    ports:
      - 2786:3306
    volumes:
      - ./db:/var/lib/mysql

  cache:
    image: redis:alpine
    container_name: ptero-cache
    restart: always

  panel:
    env_file: .env
    image: ccarney16/pterodactyl-panel:latest
    container_name: ptero-panel
    depends_on:
      - cache
      - mysql
    restart: always
    volumes:
      - ./data/data:/data
    expose:
      - 80
    environment:
      VIRTUAL_HOST: ptero.domain.com
      LETSENCRYPT_HOST: ptero.domain.com
      LETSENCRYPT_EMAIL: email@example.com
    networks:
      - proxy

  daemon:
    depends_on:
      - panel
    image: ccarney16/pterodactyl-daemon:latest
    container_name: ptero-daemon
    expose:
      - 8080
    environment:
      VIRTUAL_HOST: node.ptero.domain.com
      VIRTUAL_PORT: 8080
      LETSENCRYPT_HOST: node.ptero.domain.com
      LETSENCRYPT_EMAIL: email@example.de
    privileged: true
    restart: always
    volumes:
      - ./data/srv/daemon/config:/srv/daemon/config
      - ./data/srv/daemon/packs:/srv/daemon/packs
      - ./data/srv/daemon-data:/srv/daemon-data

      - ./data/tmp/pterodactyl:/tmp/pterodactyl

      - /etc/localtime:/etc/localtime

      - ${DOCKER_ROOT:-/var/lib/docker}:${DOCKER_ROOT:-/var/lib/docker}
      - ${DOCKER_SOCKET:-/var/run/docker.sock}:${DOCKER_SOCKET:-/var/run/docker.sock}

networks:
  proxy:
    external:
      name: nginx-proxy
```

My daemon config looks like this:
```
{
  "web": {
    "host": "127.0.0.1",
    "listen": 8080,
    "ssl": {
      "enabled": false,
      "certificate": "/etc/letsencrypt/live/ptero.domain.com/fullchain.pem",
      "key": "/etc/letsencrypt/live/ptero.domain.com/privkey.pem"
    }
  },
  "docker": {
    "container": {
      "user": 500
    },
    "network": {
      "name": "host",
      "interfaces": {
        "v4": {
          "subnet": "172.18.2.0/16",
          "gateway": "172.18.2.1"
        }
      }
    },
    "socket": "/var/run/docker.sock",
    "autoupdate_images": true,
    "timezone_path": "/etc/localtime",
    "interface": "127.0.0.1"
  },
  "filesystem": {
    "server_logs": "/tmp/pterodactyl"
  },
  "internals": {
    "disk_use_seconds": 30,
    "set_permissions_on_boot": true,
    "throttle": {
      "enabled": true,
      "kill_at_count": 5,
      "decay": 10,
      "lines": 1000,
      "check_interval_ms": 100
    }
  },
  "sftp": {
    "path": "/srv/daemon-data",
    "ip": "0.0.0.0",
    "port": 2020,
    "keypair": {
      "bits": 2048,
      "e": 65537
    }
  },
  "logger": {
    "path": "logs/",
    "src": false,
    "level": "info",
    "period": "1d",
    "count": 3
  },
  "remote": {
    "base": "http://ptero.domain.com"
  },
  "uploads": {
    "size_limit": 100
  },
  "keys": [
    "key"
  ]
}
```

I also tried to bind the web server to the IP `0.0.0.0` instead of `127.0.0.1`. Doesn't help.

Everything starts without errors. The output of the daemon looks like that:
```
04:34:34.131Z  INFO wings: + ------------------------------------ +
04:34:34.133Z  INFO wings: | Running Pterodactyl Daemon v0.6.12    |
04:34:34.133Z  INFO wings: |        https://pterodactyl.io        |
04:34:34.133Z  INFO wings: |  Copyright 2015 - 2019 Dane Everitt  |
04:34:34.133Z  INFO wings: + ------------------------------------ +
04:34:34.134Z  INFO wings: Loading modules, this could take a few seconds.
04:34:34.721Z  INFO wings: Modules loaded, starting Pterodactyl Daemon...
04:34:34.818Z  INFO wings: Configuring user pterodactyl (id: 500) as the owner of all server files.
04:34:34.822Z  INFO wings: Configuring timezone file location...
04:34:34.822Z  INFO wings: Checking container networking environment...
04:34:34.835Z  INFO wings: Found network interface for daemon: host
04:34:34.835Z  INFO wings: Ensuring correct network interface for containers...
04:34:34.842Z  WARN wings: Detected daemon configuation using HOST NETWORK for server containers. This can expose the host network stack to programs running in containers!
04:34:34.842Z  INFO wings: Gateway detected as 127.0.0.1 - using host network.
04:34:34.844Z  INFO wings: Contacting panel to retrieve a list of currrent Eggs available to the node.
04:34:35.075Z  INFO wings: Checking existing eggs against Panel response...
04:34:36.116Z  INFO wings: Beginning server initialization process.
04:34:36.118Z  INFO wings: Configuring websocket for daemon stats...
04:34:36.119Z  INFO wings: Configuring internal SFTP server...
04:34:36.142Z  INFO wings: Pterodactyl Daemon is up-to-date!
04:34:36.142Z  INFO wings: Pterodactyl Daemon is now listening for insecure connections on 127.0.0.1:8080
```

Finally, my .env file:
```
MYSQL_ROOT_PASSWORD=rpassword
MYSQL_DATABASE=pterodactyl
MYSQL_USER=ptero
MYSQL_PASSWORD=password

##
# Container Variables
##

SSL=false
SSL_CERT="/etc/certs/cert.pem"
SSL_CERT_KEY="/etc/certs/cert.key"

# Disable's runtime workers & cronjob (this is useful if you want to run these in another container)
DISABLE_WORKERS=false

##
# Panel Variables
# These variables can be used within pterodactyl.conf (.env when symlinked 
# into the docker webroot). These variables are also set via pterodactyl:env
# and pterodactyl:mail.
##
APP_URL=https://ptero.domain.com/

TIMEZONE=UTC

CACHE_DRIVER=memcached

# Rely on an external source so we can put the panel container down when updates are needed
REDIS_HOST=cache
REDIS_PORT=6379

DB_HOST=domain.com
DB_PORT=2786
DB_DATABASE=pterodactyl
DB_USERNAME=ptero
DB_PASSWORD=password

MAIL_DRIVER=mail
MAIL_FROM=admin@localhost
MAIL_FROM_NAME="Pterodactyl Panel"

TRUSTED_PROXIES=127.0.0.1

DOCKER_ROOT=/var/lib/docker
DOCKER_SOCKET=/var/run/docker.sock
```

When I now go to `https://node.ptero.domain.com`, I get a Bad Request error.
The proxy log prints the following output:
```
2020/03/02 04:32:02 [error] 16#16: *75 no live upstreams while connecting to upstream, client: IP, server: node.ptero.domain.com, request: "OPTIONS /v1 HTTP/2.0", upstream: "http://node.domain.com/v1", host: "node.domain.com", referrer: "https://ptero.domain.com/admin/nodes"
node.domain.com IP - - [02/Mar/2020:04:32:02 +0000] "OPTIONS /v1 HTTP/2.0" 502 559 "https://ptero.domain.com/admin/nodes" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.122 Safari/537.36"
```

I really do not know what to do now, because I tried almost everything possible :/
